---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Веб-сайт должен быть разработан таким образом, чтобы пользователи могли легко и быстро понять, как им пользоваться, без необходимости в дополнительном обучении или сложных инструкций.
  - Веб-сайт должен быть адаптивным и масштабируемым, чтобы обеспечить удобство использования на различных устройствах, включая мобильные телефоны и планшеты.
  - Сайт должен быть протестирован и обеспечивать корректное отображение и функциональность на последних версиях популярных браузеров, таких как Google Chrome, Mozilla Firefox, Safari и Microsoft Edge
  - Сайт должен быть разработан с учетом простоты и удобства использования, чтобы пользователи могли выполнять необходимые задачи без лишних сложностей или запутанности.
